---
git_name: wapi
git_repo: "https://github.com/vengaar/{{ git_name }}.git"
git_clone: false
wapi_user: wapi
wapi_port: 8042
wapi_base_url: http://{{ ansible_default_ipv4.address }}:{{ wapi_port }}
os_version: "{{ ansible_distribution }}/{{ ansible_distribution_major_version }}"
required:
  os:
    Fedora: 28
    Ubuntu: 18
wapi_ansible_facts_folder: ~/ansible-facts
...
