---
- hosts: localhost
  gather_facts: true
  pre_tasks:
    - name: Ensure pre-requiste
      assert:
        that:
          - ansible_distribution == "Fedora"
          - ansible_distribution_major_version|int >= 29
  roles:
    - role: setup
      git_clone: false
      wapi_user: "{{ ansible_user_id }}"
...